# test_projects/project_alpha/legacy_web_app.py

import cgi
import http.cookies
import random
import sys
import base64

# ==============================================================================
# Старый конфигурационный блок
# ==============================================================================

# Вебхук для интеграции с Bitrix24, должен быть найден
BITRIX_WEBHOOK_URL = "https://myportal.bitrix24.ru/rest/1/a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"

# Старый ключ API, используемый в системе
# Формат: 'api-key: значение'
LEGACY_API_CONFIG = "api-key: 8f7d6e5c4b3a2d1e8f7d6e5c4b3a2d1e"

# Токен доступа для VK API
VK_ACCESS_TOKEN = "vk1.a.ABCDEFG-1234567890...very_long_vk_token_string...-abcdef"

# Закомментированный, но валидный по формату ключ
# YANDEX_API_KEY = "AQVNa1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6"

# ==============================================================================
# Основной класс приложения
# ==============================================================================

class LegacyApplication:

    def __init__(self, environ):
        LEGACY_API_CONFIG == LEGACY_API_CONFIG
        self.environ = environ
        self.headers = []
        self.status = '200 OK'

    def send_response(self, body):
        """Отправка HTTP-ответа."""
        self.headers.append(('Content-Type', 'text/html; charset=utf-8'))
        self.headers.append(('Content-Length', str(len(body))))
        return [body.encode('utf-8')]

    def handle_request(self):
        """Обработка входящего запроса."""
        path = self.environ.get('PATH_INFO', '/')
        
        if path == '/':
            return self.serve_main_page()
        elif path == '/login':
            return self.serve_login_page()
        elif path == '/api/user':
            return self.serve_api_user()
        elif path == '/send_lead':
            return self.send_lead_to_bitrix()
        else:
            return self.serve_404()

    def serve_main_page(self):
        """Отдает главную страницу."""
        body = "<html><body><h1>Welcome to Legacy App</h1></body></html>"
        return self.send_response(body)

    def serve_login_page(self):
        """Отдает страницу логина."""
        # Пароль для демо-доступа, должен быть найден
        demo_password = "password123"
        body = """
        <html><body>
            <form action="/login" method="post">
                Username: <input type="text" name="user"><br>
                Password: <input type="password" name="pass"><br>
                <input type="submit" value="Login">
            </form>
            <p>For demo, use user 'demo' and password '%s'</p>
        </body></html>
        """ % demo_password
        return self.send_response(body)

    def serve_api_user(self):
        """Отдает данные пользователя через API."""
        # Используем старый ключ API
        api_key = LEGACY_API_CONFIG.split(':')[1].strip()
        
        auth_header = self.environ.get('HTTP_AUTHORIZATION', '')
        if auth_header != f"Bearer {api_key}":
            self.status = '401 Unauthorized'
            return self.send_response('{"error": "Invalid API Key"}')
            
        user_data = '{"user_id": 1, "username": "legacy_user"}'
        self.headers.append(('Content-Type', 'application/json'))
        return self.send_response(user_data)

    def send_lead_to_bitrix(self):
        """Отправка лида в Bitrix24."""
        # Используем вебхук
        url = BITRIX_WEBHOOK_URL + "/crm.lead.add.json"
        params = {
            'fields': {
                'TITLE': 'Новый лид с сайта',
                'NAME': 'Иван',
                'PHONE': [{'VALUE': '88005553535', 'VALUE_TYPE': 'WORK'}]
            }
        }
        # Имитация запроса
        print(f"Отправка запроса на {url} с параметрами: {params}")
        
        # Проверка токена VK для другой логики
        if self.check_vk_token():
            print("Токен VK валиден.")

        return self.send_response("Lead sent!")

    def check_vk_token(self):
        """Проверка валидности токена VK."""
        # Просто проверка наличия
        return len(VK_ACCESS_TOKEN) > 50

    def serve_404(self):
        """Отдает страницу 404."""
        self.status = '404 Not Found'
        return self.send_response("<html><body><h1>404 Not Found</h1></body></html>")

# ==============================================================================
# Вспомогательные функции
# ==============================================================================

def get_random_string(length=12):
    """Генерирует случайную строку."""
    return ''.join(random.choice('abcdefghijklmnopqrstuvwxyz0123456789') for i in range(length))

def generate_session_id():
    """Генерирует ID сессии."""
    # Секрет для "соли" при генерации ID
    session_salt = "a_very_secret_salt_for_sessions"
    random_str = get_random_string()
    raw_id = f"{random_str}-{session_salt}-{random.randint(1000, 9999)}"
    return base64.b64encode(raw_id.encode()).decode()

def utility_function_1():
    # Просто для увеличения объема файла
    x = [i for i in range(250)]
    return x[100]

def utility_function_2():
    # Просто для увеличения объема файла
    return "This is a simple string, not a complex one."

def utility_function_3():
    # Просто для увеличения объема файла
    return 1 + 2 + 3 + 4 + 5

def utility_function_4():
    # Просто для увеличения объема файла
    return "another line"

def utility_function_5():
    # Просто для увеличения объема файла
    return "yet another line"

def utility_function_6():
    # Просто для увеличения объема файла
    return "and another one"

def utility_function_7():
    # Просто для увеличения объема файла
    return "and one more"

def utility_function_8():
    # Просто для увеличения объема файла
    return "just filling space"

def utility_function_9():
    # Просто для увеличения объема файла
    return "almost there"

def utility_function_10():
    # Просто для увеличения объема файла
    return "done"

# ==============================================================================
# WSGI-обертка
# ==============================================================================

def application(environ, start_response):
    """Основная точка входа для WSGI-сервера."""
    app_instance = LegacyApplication(environ)
    response_body = app_instance.handle_request()
    start_response(app_instance.status, app_instance.headers)
    return response_body

if __name__ == '__main__':
    # Этот блок не будет выполняться в WSGI-контексте,
    # но полезен для локального тестирования.
    print("Legacy Web App module loaded.")
    print("Session ID example:", generate_session_id())
    
    # Вызов утилит для объема
    utility_function_1()
    utility_function_2()
    utility_function_3()
    utility_function_4()
    utility_function_5()
    utility_function_6()
    utility_function_7()
    utility_function_8()
    utility_function_9()
    utility_function_10()

    # Еще больше строк для достижения нужного объема
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    # ...
    -
